### PR TITLE
test: migrating all enzyme tests over to RTL

### PR DESCRIPTION
**Pull request by erunion**
[][demo] |
:---:|

## 🧰 Changes

* [x] Migrates all tests that were using [enzyme](https://npm.im/enzyme) over to using RTL.

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io

### CODE REVIEW

**Comment by kellyjosephprice** [comment]
sickos.gif

**Review by kellyjosephprice — APPROVED** [review]
Thanks so much for doing this! This looks like some of the least fun work to do. But also, much appreciated.

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.38.4-next.1</b>](/readmeio/markdown/releases/tag/v6.38.4-next.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.38.4</b>](/readmeio/markdown/releases/tag/v6.38.4)
<br>

**Pull request merged**
