### PR TITLE
fix: use different font size for h1

### PR DESCRIPTION
**Pull request by mjcuva**
## 🧰 Changes

Right now h1 and h2 are the same size, this is making h1s slightly larger. I'm not 100% sure how to test this, so we should make sure to test it in readme before releasing!

Fixes RM-1364

### CODE REVIEW

**Review by rafegoldberg — APPROVED** [review]

**Comment by rafegoldberg** [comment]
I think you need to update the visual test snapshots. I think it requires docker? (That, or @kellyjosephprice’s help!)

**Comment by kellyjosephprice** [comment]
> Looks like you need to update the visual test snapshots. Which I think requires some docker setup? (That, or @kellyjosephprice’s help!)

I get clever-er and upload the diffs and the snapshots. You can review the diffs, then commit the updated snapshots.

image

The docker PR (#104) is still awaiting review.

**Review by kellyjosephprice — APPROVED** [review]
LGTM

The snapshots definitely caught the change in size.

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.29.1-next.1</b>](/readmeio/markdown/releases/tag/v6.29.1-next.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.30.0</b>](/readmeio/markdown/releases/tag/v6.30.0)
<br>

**Pull request merged**
