### PR TITLE
docs: update custom CSS guidance

### PR DESCRIPTION
**Pull request by kanadgupta**
[][demo] |
:---:|

## 🧰 Changes

Updates our Custom CSS guidance to reflect the updated markup in the new docs design!

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-172.herokuapp.com
[prod]: https://rdmd.readme.io/docs/custom-css

### CODE REVIEW

**Comment by kanadgupta** [comment]
@rafegoldberg tagging you for a review in case you had any feedback on content or semantics... I'm leaving this as a draft PR since there's still need to work on some other knowledge base pages before this is ready to be merged in!

**Review by rafegoldberg — APPROVED** [review]
Content updates look good to me!

**Comment by kanadgupta** [comment]
Cleaned up the language and added a link to the migration guide, should be good to go now!

**Review by rafegoldberg — APPROVED** [review]
LGTM!

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.27.3-next.1</b>](/readmeio/markdown/releases/tag/v6.27.3-next.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.28.0</b>](/readmeio/markdown/releases/tag/v6.28.0)
<br>

**Pull request merged**
