### PR TITLE
fix: variable stringification

### PR DESCRIPTION
**Pull request by kellyjosephprice**
[][demo] | Fixes CX-400
:---:|:---:

## 🧰 Changes

Fixes the variable compiler to output the original text

Co-authored-by: Julia Hotaling <42787244+julshotal@users.noreply.github.com>

### CODE REVIEW

**Comment by kellyjosephprice** [comment]
@julshotal do you have a ticket for this?

**Review by julshotal — APPROVED** [review]
Running this locally, variables are rendering in changelog excerpts now!

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.30.3-next.3</b>](/readmeio/markdown/releases/tag/v6.30.3-next.3)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.30.3</b>](/readmeio/markdown/releases/tag/v6.30.3)
<br>

**Pull request merged**
