### PR TITLE
feat: glossary niceness and more

### PR DESCRIPTION
**Pull request by kellyjosephprice**
| [![PR App][icn]][demo] | Fix RM-9669, RM-9767 |
| :--------------------: | :------------------: |

## 🧰 Changes

Refactors glossary stuff.

1. `<GlossaryItem />` -> `<Glossary />`
   I kept typing the wrong thing, so...

2. `<Glossary term="parliament" />` -> `<Glossary>parliament</Glossary>`
   Because greg said so.

3. Moves the Glossary, Variables, and BaseUrl contexts into this repo. The values are now passed in as options. This should make `mdx-renderer` simpler.

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

### CODE REVIEW

**Review by jennspencer — APPROVED** [review]
LGTM but maybe change `<Variable variable="thing" />` to like `var="thing"` because i've now read 'variable' too many times and it's no longer a real word to me

**Comment by kellyjosephprice** [comment]
> LGTM but maybe change `<Variable variable="thing" />` to like `var="thing"` because i've now read 'variable' too many times and it's no longer a real word to me

Should it be similar to Glossary:
```
<Variable>thing</Variable>
```

**Comment by jennspencer** [comment]
> > LGTM but maybe change `<Variable variable="thing" />` to like `var="thing"` because i've now read 'variable' too many times and it's no longer a real word to me
> 
> Should it be similar to Glossary:
> 
> ```
> <Variable>thing</Variable>
> ```

that works for a glossary item because you're actually displaying the word, but it feels weird for a variable?

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.75.0-beta.36</b>](/readmeio/markdown/releases/tag/v6.75.0-beta.36)
<br>

**Pull request merged**
