### PR TITLE
feat: mermaid diagrams

### PR DESCRIPTION
**Pull request by trishaprile**
[![PR App][icn]][demo] | Fix RM-10840
:-------------------:|:----------:

## 🧰 Changes
- Support `Mermaid` as a code block language
- If it's a single diagram, render without a code block
- If there's multiple tabs, render within a code block

image

image

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

### CODE REVIEW

**Review by kellyjosephprice — APPROVED** [review]
Hell yea.

**Comment by trishaprile** [comment]
@kellyjosephprice are any of theses failed tests valid

**Comment by kellyjosephprice** [comment]
> @kellyjosephprice are any of theses failed tests valid

No, but lets hold off an merging till we get the build fixed.

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v7.7.0</b>](/readmeio/markdown/releases/tag/v7.7.0)
<br>

**Pull request merged**
