### PR TITLE
style(anchor): menu item styling for doc links

### PR DESCRIPTION
**Pull request by runnabro**
[![PR App][icn]][demo] | Fix RM-XYZ
:-------------------:|:----------:

## 🧰 Changes

Broken:
Edit Documentation · ReadMe-20220927-113238@2x

Fixed:
Edit Documentation · ReadMe-20220927-112844@2x

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

### CODE REVIEW

**Review by ellierossuck — APPROVED** [review]
Nice one! ✨

**Review by kellyjosephprice — COMMENTED** [review]
Instead of adding classes to the Anchor, maybe we could export the `getHref` function? Then the link editor menu can import it and use it to generate the proper url?

**Comment by runnabro** [comment]
@kellyjosephprice How's this?

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.52.2</b>](/readmeio/markdown/releases/tag/v6.52.2)
<br>

**Pull request merged**
