### PR TITLE
fix: magic tables collect all cells

### PR DESCRIPTION
**Pull request by kellyjosephprice**
| Fixes CX-188
|:---:

## 🧰 Changes

Previously, the `tableFlattening` function was assuming that tables only had plain text. In effect, if you have any markdown formatting in a table cell, it and anything after it would not be indexed!

## 🧬 QA & Testing

You can verify that the test is sane, but this really needs to be end to end
tested.

### CODE REVIEW

**Comment by kellyjosephprice** [comment]
Sorry, not ready for review. Double checking that my test is doing the right thing, and I'm not sure what's actually causing the problem...

**Comment by kellyjosephprice** [comment]
> Sorry, not ready for review. Double checking that my test is doing the right thing, and I'm not sure what's actually causing the problem...

Ok, it's ready

**Review by gratcliff — APPROVED** [review]
This is much better.

**Review by rafegoldberg — APPROVED** [review]
Oh nice, this looks great. Will these changes fix the issue with search results not returning table text? Seems like it might!

**Comment by kellyjosephprice** [comment]
> Oh nice, this looks great. Will these changes fix the issue with search results not returning table text? Seems like it might!

I haven't tested it in the app yet, but I'm assuming so.

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.26.6-next.1</b>](/readmeio/markdown/releases/tag/v6.26.6-next.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.26.6</b>](/readmeio/markdown/releases/tag/v6.26.6)
<br>

**Pull request merged**
