### PR TITLE
fix(toc): wrap children in an <li> for screen readers controls

### PR DESCRIPTION
**Pull request by billhimmelsbach**
[][demo] | Fixes RM-1554
:---:|:---:

## 🧰 Changes

- Wrap children of the Table of Contents component in an `<li>` to conform to the structure preferred for screen reader navigation
- Works in conjunction with a small style change in the main `@readmeio/readme` repo:
https://github.com/readmeio/readme/pull/4831

## 🧬 QA & Testing

- Do accessibility tests (lighthouse/axe) now detect a compatible `ul` structure?
_before_
Screenshot-Google Chrome-Markdown Demo-on-07-21-2021-at-15 31 03
_after_
Screenshot-Google Chrome-Markdown Demo-on-07-21-2021-at-15 35 07

By adding a class to the children `li`, we can be more specific with our css in the accompanying PR:
https://github.com/readmeio/readme/pull/4831

Which means now there's no difference in styling, while keeping the better structure for screen readers 🎉
new-vs-old-styling
(screenshots are from local `@readme/readme` branch using these markdown changes. The local markdown playground still uses thee old `bundle-hub2.css` for its CSS, so there's some diff there in the PR app, but won't be present on `@readme/readme`)

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-232.herokuapp.com
[prod]: https://developers.readme.io

### CODE REVIEW

**Comment by billhimmelsbach** [comment]
Converting back to draft since there's some changes that still need to be made to fix the styling.

**Comment by billhimmelsbach** [comment]
By adding a class to the children `li`, we can be more specific with our css in the accompanying PR:
https://github.com/readmeio/readme/pull/4831

Which means now there's no difference in styling, while keeping the better structure for screen readers 🎉
new-vs-old-styling
(screenshots are from local `@readme/readme` branch using these markdown changes. The local markdown playground still uses thee old `bundle-hub2.css` for its CSS, so there's some diff there, but won't be present on `@readme/readme`)

**Review by rafegoldberg — APPROVED** [review]

**Review by julshotal — APPROVED** [review]

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.30.1-next.3</b>](/readmeio/markdown/releases/tag/v6.30.1-next.3)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.30.1</b>](/readmeio/markdown/releases/tag/v6.30.1)
<br>

**Pull request merged**
