### PR TITLE
test(heading): add test for aria-labels being passed properly

### PR DESCRIPTION
**Pull request by macuzi**
[][demo] | Fixes RM-1571
:---:|:---:

## 🧰 Changes

- Test if aria-label is being applied correctly — Related to this [PR](https://github.com/readmeio/markdown/pull/230)

## 🧬 QA & Testing

Does the snapshot of the heading component look as expected?

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-234.herokuapp.com
[prod]: https://developers.readme.io

### CODE REVIEW

**Comment by macuzi** [comment]
This test covers h2's (since our widgets generate them). But since markdown headers also generate skip links, it might be a good idea to test those down the road.

**Review by kellyjosephprice — APPROVED** [review]
LGTM

**Review by billhimmelsbach — APPROVED** [review]
Yay! Looks great @macuzi! 🎉

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.31.0</b>](/readmeio/markdown/releases/tag/v6.31.0)
<br>

**Pull request merged**
