### PR TITLE
fix: tabindex for code and callouts without h3

### PR DESCRIPTION
**Pull request by runnabro**
[![PR App][icn]][demo] | Fix RM-XYZ
:-------------------:|:----------:

## 🧰 Changes

Code Blocks
* You should be able to tab to code blocks so you can scroll within them (though you can also tab to them now even when not scrollable—I'm thinking that's a good trade-off)
* Added tab roles to the code blocks

Callouts
* Maybe the riskiest change here is that we're removing the `<h3>` tag from the titles of callouts and replacing it with `<p>` tags. This is b/c we were triggering semantic heading order issues in accessibility tests.

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-796.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

### CODE REVIEW

**Review by kellyjosephprice — APPROVED** [review]
Nice.

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.65.2-beta.1</b>](/readmeio/markdown/releases/tag/v6.65.2-beta.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.66.0-beta.1</b>](/readmeio/markdown/releases/tag/v6.66.0-beta.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.65.2</b>](/readmeio/markdown/releases/tag/v6.65.2)
<br>

**Pull request merged**
