### PR TITLE
ci: add another missing page category to get our docs syncing

### PR DESCRIPTION
**Pull request by kanadgupta**
## 🧰 Changes

So it looks like the sync step was _**partiallly**_ fixed in #171 (see [this page](https://rdmd.readme.io/docs/custom-css), which successfully updated!), but there was one page that I overlooked which ultimately [caused the workflow to fail](https://github.com/readmeio/markdown/runs/2896825988?check_suite_focus=true#step:8). Since this is a simple test page, I'm just backfilling the category for this page with our existing catch-all "Tests" category.

## 🧬 QA & Testing

I actually ran the `rdme` command locally this time and confirmed that the script ran successfully 🎉  If I am not crazy and you can in fact see [this page](https://rdmd.readme.io/docs/callouts-tests) in ReadMe, we should be good to go! See below for the full output when I ran the command locally:
image

### CODE REVIEW

**Review by kellyjosephprice — CHANGES_REQUESTED** [review]
:hugs: This looks good!

Except, when I run `npm run sync -- --key ...`, it appears to be adding a new `callouts-tests` page each time, and getting  a new slug?

```
> rdme docs ./docs --version=2 "--key" "..."

[
  {
    metadata: { image: [], title: '', description: '' },
    api: { method: 'get', url: '', auth: 'required', params: [] },
    next: { description: '', pages: [] },
    title: 'Callouts Tests',
    updates: [],
    type: 'basic',
    slug: 'callouts-tests-2',
    excerpt: '',
    body: '> 👍 Success\n' +
      '> \n' +
      '> <a href="http://www.google.com">Vitae</a> <span>reprehenderit</span> at aliquid error voluptates eum dignissimos.',
    order: 999,
    isReference: false,
    hidden: true,
    sync_unique: '',
    link_url: '',
    link_external: false,
    pendingAlgoliaPublish: true,
    previousSlug: '',
    slugUpdatedAt: '2021-06-23T16:56:01.747Z',
    _id: '60d384b6c16abe0064268b8e',
    category: '5fdf9fc9c2a7ef443e937315',
    lastUpdatedHash: '9cf9709b1584318eb4882ae8274f3588f7966579',
    createdAt: '2021-06-23T19:00:06.428Z',
    updatedAt: '2021-06-23T19:00:06.428Z',
    version: '5fdf7610134322007389a71b',
    __v: 0,
    isApi: false,
    id: '60d384b6c16abe0064268b8e'
  },
  '`callouts` not updated. No changes.',
  '`code-block-tests` not updated. No changes.',
  '`code-blocks` not updated. No changes.',
  '`custom-css` not updated. No changes.',
  '`embeds` not updated. No changes.',
  '`features` not updated. No changes.',
  '`getting-started` not updated. No changes.',
  '`headings` not updated. No changes.',
  '`images` not updated. No changes.',
  '`lists` not updated. No changes.',
  '`syntax-extensions` not updated. No changes.',
  '`table-of-contents-tests` not updated. No changes.',
  '`tables` not updated. No changes.',
  '`variable-tests` not updated. No changes.'
]
```

**Comment by kanadgupta** [comment]
@kellyjosephprice shit great catch here... will look into this!

**Comment by kanadgupta** [comment]
@kellyjosephprice good to go now! Took a second but turns out `rdme` doesn't like when the slug and the file name are slightly different 😅 here's the output when I try running it several times over:
```sh
➜  markdown git:(docs/add-another-missing-category) ✗ npm run sync -- --key=<redacted>

> @readme/markdown@6.27.2 sync
> rdme docs ./docs --version=2 "--key=<redacted>"

[
  '`callout-tests` not updated. No changes.',
  '`callouts` not updated. No changes.',
  '`code-block-tests` not updated. No changes.',
  '`code-blocks` not updated. No changes.',
  '`custom-css` not updated. No changes.',
  '`embeds` not updated. No changes.',
  '`features` not updated. No changes.',
  '`getting-started` not updated. No changes.',
  '`headings` not updated. No changes.',
  '`images` not updated. No changes.',
  '`lists` not updated. No changes.',
  '`syntax-extensions` not updated. No changes.',
  '`table-of-contents-tests` not updated. No changes.',
  '`tables` not updated. No changes.',
  '`variable-tests` not updated. No changes.'
]
➜  markdown git:(docs/add-another-missing-category) ✗ npm run sync -- --key=<redacted>

> @readme/markdown@6.27.2 sync
> rdme docs ./docs --version=2 "--key=<redacted>"

[
  '`callout-tests` not updated. No changes.',
  '`callouts` not updated. No changes.',
  '`code-block-tests` not updated. No changes.',
  '`code-blocks` not updated. No changes.',
  '`custom-css` not updated. No changes.',
  '`embeds` not updated. No changes.',
  '`features` not updated. No changes.',
  '`getting-started` not updated. No changes.',
  '`headings` not updated. No changes.',
  '`images` not updated. No changes.',
  '`lists` not updated. No changes.',
  '`syntax-extensions` not updated. No changes.',
  '`table-of-contents-tests` not updated. No changes.',
  '`tables` not updated. No changes.',
  '`variable-tests` not updated. No changes.'
]
```

**Review by kellyjosephprice — APPROVED** [review]
Thanks for fixing this!

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.27.3-next.2</b>](/readmeio/markdown/releases/tag/v6.27.3-next.2)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.28.0</b>](/readmeio/markdown/releases/tag/v6.28.0)
<br>

**Pull request merged**
