### PR TITLE
fix: use TLS for npm release

### PR DESCRIPTION
**Pull request by kellyjosephprice**
## 🧰 Changes

Update the npm registry URL to use TLS.

### CODE REVIEW

**Comment by erunion** [comment]
Can probably just remove the publish config all together

**Review by erunion — APPROVED** [review]

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.32.0-next.3</b>](/readmeio/markdown/releases/tag/v6.32.0-next.3)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.32.1-next.1</b>](/readmeio/markdown/releases/tag/v6.32.1-next.1)
<br>

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.32.1</b>](/readmeio/markdown/releases/tag/v6.32.1)
<br>

**Pull request merged**
