### PR TITLE
fix: react warning in image component

### PR DESCRIPTION
**Pull request by kanadgupta**
[![PR App][icn]][demo] |
:-------------------:|

## 🧰 Changes

I see these errors show up all the time within ReadMe and decided to go down a little rabbit hole to address it:

CleanShot 2023-06-14 at 15 10 57@2x

CleanShot 2023-06-14 at 15 18 19@2x

## 🧬 QA & Testing

I also wrote a few tests to confirm that the `alt` text attribute isn't affected in various scenarios. If you run those tests, you can confirm that the React warning disappears ✨

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

### CODE REVIEW

**Comment by trishaprile** [comment]
hmm when running the test locally it looks like there's a `div` that wraps the `span`?
image

**Comment by kanadgupta** [comment]
@trishaprile yeah so I believe that test is only looking for a partial match (hence an empty string will pass the test)... I've tried it with and without the `div` locally and nothing seems to work 😕

**Comment by kanadgupta** [comment]
Ok ready for review again! I rewrote the assertion for the test in https://github.com/readmeio/markdown/pull/763/commits/3cd7d1c73ed9aa73121d0c1ef56a8522fb5fe6f4, let me know what y'all think 😬

**Comment by erunion** [comment]
you dropped this 👑

**Review by trishaprile — APPROVED** [review]
nice im ok with that test 😅 thanks for addressing this warning! 🕺

**Comment by rafegoldberg** [comment]
## This PR was released!

🚀 Changes included in [<b>v6.62.4</b>](/readmeio/markdown/releases/tag/v6.62.4)
<br>

**Comment by brendanluna** [comment]
Thanks a ton for fixing this! @dannobytes and I have had this as a Refactor Club item for awhile, so I'll close it out now 🙌 

https://linear.app/readme-io/issue/RM-5913/improper-lazy-attr-value-on-readmemarkdown-component

**Comment by dannobytes** [comment]
> Thanks a ton for fixing this! @dannobytes and I have had this as a Refactor Club item for awhile, so I'll close it out now 🙌
> 
> https://linear.app/readme-io/issue/RM-5913/improper-lazy-attr-value-on-readmemarkdown-component

OMG, same!! 🤩 This console warning was very annoying

**Pull request merged**
